version: "3.8"

services:
  ####################
  # Maildev Container
  ####################
  maildev:
    ports:
      - "${MAILDEV_HTTP_PORT}:80"
      - "${MAILDEV_SMTP_PORT}:25"

  ####################
  # Adminer Container
  ####################
  adminer:
    ports:
      - "${ADMINER_PORT}:8080"

  ####################
  # PHPMyAdmin Container
  ####################
  phpmyadmin:
    ports:
      - "${PMA_PORT}:80"

  ####################
  # PHP Apache Container
  ####################
  php-apache:
    ports:
      - "${APACHE_PORT}:80"

  ####################
  # Mariadb
  ####################
  mariadb:
    ports:
      - "${MYSQL_PORT}:3306"
